### PR TITLE
DEVXT-1781: Upgrade backstage backend

### PR DESCRIPTION
**Pull request by MonicaG**
- **update to version 1.32.4**
- **updated to use new backend system**

Major changes:

- Removed all of the `packages/backend/src/plugins` files 
  - The catalog and stackoverflow configuration that were done in the catalog.ts and search.ts files were moved into the `app-config.production.yaml` file
  - Permission code was moved into new `packages/backend/src/extensions/permissionsPolicyExtension.ts` file
  - I also tried to clean up the spread of configuration. The stackoverflow and auth configs are now part or `app-config.production.yaml` file instead of having to be defined in every `values.*.yaml` file in the gitops repo.
- Added the `ProxiedSignInPage`  to the `packages/app/src/App.tsx` file. 
  - This will allow us to use the site as before
  - updated the auth configuration in `app-config.production.yaml` to allow this process
- Removed the `LEGACY_BACKEND_START` from the Dockerfile as we are now using the new backend
  - Also updated the Dockerfile to not pin the image tag. This will let us get security updates if available on a new build and is Docker's recommendation

Notes: 
- There is some whitespace formatting changes with the checkin because of our husky processor. These formatting changes will start to settle down as we update files.
- Backstage has updated to yarn 4. I have created a separate ticket for that, as this PR is large enough.

### CODE REVIEW

**Review by sheaphillips — COMMENTED** [review]
Taking a look at this now...

**Review by sheaphillips — APPROVED** [review]
I've looked through the changes and also brought this up locally. I don't have any  concerns, other than maybe capturing a sample app config sometwhere for us to use internally, and maybe updating the README?

**Review by oomIRL — APPROVED** [review]
Looks good!

**Comment by MonicaG** [comment]
> I've looked through the changes and also brought this up locally. I don't have any concerns, other than maybe capturing a sample app config sometwhere for us to use internally, and maybe updating the README?

I've updated the README file and provided an `app-config.local.yaml.template` file

**Pull request merged**
